PR: `Link.regex/0` `Link.find/1` and `Link.find_replace_compact/1` issue #4
dwyl/link pull request #5
Opened 2023-08-01 02:42 UTC by nelsonic

As the title suggests, this PR creates the functions we need for finding and compacting `URLs` in our `MVP` ref: https://github.com/dwyl/mvp/issues/141

2023-08-01 04:03 UTC, nelsonic commented
@LuchoTurtle please review + merge when you can. Thanks. 👌

2023-08-01 08:35 UTC, nelsonic commented
@LuchoTurtle on reading my own code I spotted a potential `Bug`: https://github.com/dwyl/link/issues/4#issuecomment-1659534045 🐞 
Gonna take a quick look at it this morning and then will re-assign back to you for review. 👌

2023-08-02 04:48 UTC, nelsonic commented
Try it: https://amemo.fly.dev/
```markdown
This is my link:
https://github.com/dwyl/mvp/issues/141#issuecomment-1657954420
it gets compacted to save screen space.
But [markdown links](https://github.com/dwyl/mvp/issues/141#issuecomment-1657954420) 
and ![images](https://i.pinimg.com/1200x/5d/fe/59/5dfe590aa252b50f8e5b35a129f617d5.jpg) are unmodified.
Try it! 😊
```

For: https://github.com/dwyl/mvp/issues/141#issuecomment-1661489434

2023-08-02 12:38 UTC, LuchoTurtle approved these changes
Awesome work! Works great ⭐

2023-08-02 12:42 UTC, LuchoTurtle commented
Thanks @nelsonic , works wonders!

I don't know if you want to support all of Github's content but two instances don't look exactly like what happens on Github.

<img width="676" alt="Screenshot 2023-08-02 at 13 41 16" src="https://github.com/dwyl/link/assets/17494745/66e24026-1e91-4a69-a7ec-bca607fba092">


this is a PR - https://github.com/dwyl/link/pull/5

this is an issue - https://github.com/dwyl/flutter-wysiwyg-editor-tutorial/issues/1#issuecomment-1646888350

this is a link to a comment - https://github.com/dwyl/flutter-wysiwyg-editor-tutorial/issues/1#issuecomment-1646888350

this is a link to a review comment - https://github.com/dwyl/link/pull/5#pullrequestreview-1558913764

this is a repo - https://github.com/dwyl/link

Do you want me to merge this nonetheless? I think these are perhaps not needed for this PR but since you've went through the trouble of implementing them, I'm wondering if it makes sense to treat these edge cases.

2023-08-02 16:45 UTC, nelsonic commented
@LuchoTurtle Good edge cases. Let's add tests for them and write the code.

```sh
https://github.com/dwyl/link/pull/5 -> dwyl/link/pull/5

https://github.com/dwyl/flutter-wysiwyg-editor-tutorial/issues/1#issuecomment-1646888350 -> dwyl/flutter-wysiwyg-editor-tutorial#1

https://github.com/dwyl/flutter-wysiwyg-editor-tutorial/issues/1#issuecomment-1646888350 -> dwyl/flutter-wysiwyg-editor-tutorial#1

https://github.com/dwyl/link/pull/5#pullrequestreview-1558913764 -> dwyl/link/pull/5

https://github.com/dwyl/link -> dwyl/link
```

2023-08-02 16:50 UTC, nelsonic commented
If we input these links:
```md
https://github.com/dwyl/link/pull/5  
https://github.com/dwyl/flutter-wysiwyg-editor-tutorial/issues/1#issuecomment-1646888350  
https://github.com/dwyl/link/pull/5#pullrequestreview-1558913764  
https://github.com/dwyl/link
```
Into the demo app: https://amemo.fly.dev we see that the Pull Request and Review Comment links aren't working:
 
<img width="946" alt="image" src="https://github.com/dwyl/link/assets/194400/7de4cf04-ddbb-4f13-9c68-983506e0db17">

I will add tests and code for these. 👨‍💻 ⏳

2023-08-03 07:29 UTC, nelsonic commented on lib/link.ex
> +    ~r|[(http(s)?):\/\/(www\.)?a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,14}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)|
If anyone has a _better_ `regex` for detecting URLs please share! 🙏

2023-08-04 09:35 UTC, nelsonic commented
@LuchoTurtle I've added the `tests` and `code` to make `PR` links work #7 
Test on the demo version: https://amemo.fly.dev/

![image](https://github.com/dwyl/link/assets/194400/4753d763-cde9-4dd2-b5c2-e7e58b2403de)

```md
https://github.com/dwyl/link spacing text  
https://github.com/dwyl/link/pull/5 more text    
https://github.com/dwyl/link/pull/5#pullrequestreview-1558913764  
more random text and a markdown link
[link](https://github.com/dwyl/link) 
```

or with the list of links you shared above:

```md
https://github.com/dwyl/link
https://github.com/dwyl/link/pull/5  
https://github.com/dwyl/flutter-wysiwyg-editor-tutorial/issues/1#issuecomment-1646888350  
https://github.com/dwyl/link/pull/5#pullrequestreview-1558913764  
```

![image](https://github.com/dwyl/link/assets/194400/843f7254-ac99-4eca-a817-14c265418aa8)

Please review & merge when you can. 🙏

2023-08-04 20:08 UTC, LuchoTurtle requested changes
Thanks for the changes 😍 .

I was testing the compacted Github links you've fixed and they seem to be working fine (although when there's a "review comment" or "regular comment", it doesn't show *exactly* like Github's with the `(comment)` string, but it's fine).

However, I've noticed a funny behaviour. Check the following video. It seems that when the string is empty, Github's compaction doesn't seem to work.


https://github.com/dwyl/link/assets/17494745/3f4ea904-39f6-4f33-8a10-c3c1c0b5c8b2

Is this desirable?
I'm going to `request changes` but I can try to get it fixed, if you want to.

2023-08-05 06:24 UTC, nelsonic commented
@LuchoTurtle thanks for this valuable real-world QA-ing. I've opened an issue: https://github.com/dwyl/link/issues/8 🆕

2023-08-05 06:44 UTC, nelsonic commented
BTW: removing the word "review" or "comment" from the hypertext is 100% desirable; they add no value in link text. 😉 ✂️

2023-08-05 06:48 UTC, nelsonic commented
@LuchoTurtle please see: https://github.com/dwyl/link/issues/8#issuecomment-1666415465 🙏

2023-08-05 06:50 UTC, nelsonic commented
https://github.com/dwyl/link/blob/d342f8fc83a67077b483f10bee906894e2578c28/lib/link.ex#L207-L208

2023-08-05 06:51 UTC, nelsonic commented on lib/link.ex
> +      # Find a link without any other text or whitespace #8
Added this doctest for #8 
Passes without modifying any cost

2023-08-05 06:52 UTC, nelsonic commented on lib/link.ex
> +      iex> Link.find_replace_compact("https://github.com/dwyl/link/pull/5#pullrequestreview-1558913764")
Added this doctest for #8 ... passes without modifying any `code`. 🤷‍♂️

2023-08-06 18:48 UTC, nelsonic commented
@LuchoTurtle PR links Working flawlessly on: https://amemo.fly.dev/
![pr-links-still-work](https://github.com/dwyl/link/assets/194400/59a638cb-48c6-48fb-b2d8-eded927a74d6)

2023-08-06 19:23 UTC, nelsonic commented on lib/link.ex
> +      iex> Link.find_replace_compact("https://github.com/dwyl/link/pull/5#pullrequestreview-1558913764")
It's working. https://github.com/dwyl/link/pull/5#issuecomment-1666943043 ✅

2023-08-06 19:23 UTC, nelsonic commented on lib/link.ex
> +      # Find a link without any other text or whitespace #8
PR links are working. https://github.com/dwyl/link/pull/5#issuecomment-1666943043 ✅

2023-08-10 17:25 UTC, nelsonic commented
@LuchoTurtle should be reviewable/mergeable now (when you get back from holidays). 👌

2023-08-11 11:53 UTC, LuchoTurtle approved these changes
lgtm!
Thanks for the changes! I've tried a few GH possibilities and it seems to work tremendously well! 🥳 

<img width="737" alt="image" src="https://github.com/dwyl/link/assets/17494745/1c1dd53e-ef40-4b5b-b35f-a46fa6f20ff9">

2023-08-11 11:54 UTC, merged

2023-08-12 04:44 UTC, nelsonic commented
@LuchoTurtle Thanks for reviewing + merge. 🙏 
Follow-up issue created: https://github.com/dwyl/link/issues/9 🙃